surf-build/surf

src/build-api.js
src/build-project-cli.js
src/clean-workdirs-cli.js
src/git-api.js

Set up a temp directory for builds and trash that directory once we successfully build (leave it around if it fails for debugging).

Create a per-build temp directory

---

README.md
src/build-project-cli.js
src/git-api.js
src/ref-server-api.js
src/ref-server-cli.js
src/run-on-every-ref-cli.js

This PR tries to fill in parameters to the CLI apps with reasonable defaults - for example, if I run `surf-build` in my project dir, it's probably a good guess that I want to build my project at the current SHA1

When parameters aren't provided, try really hard to find them

---

src/build-project-cli.js
src/github-api.js
src/run-on-every-ref-cli.js

If we run a simple `surf-build` against a repo that has an SSH URL for a remote, we need to transmogrify it to an HTTPS URL.

Handle SSH Remote URLs

---

package.json
src/ref-server-api.js
views/status.jade

This PR creates a status page that lets you see the currently polling build clients

Create a basic status page

---

package.json
src/git-api.js
src/github-api.js
src/publish-tag-cli.js
src/publish-tag-main.js

This PR creates a new command `surf-publish` that will publish artifacts to GitHub as a Release given a Tag:
```
Creates a release for the given tag by downloading all of the build
artifacts and reuploading them
Options:
-r, --repo  The repository to clone
-t, --tag   The tag to download releases for
Some useful environment variables:
GITHUB_TOKEN - the GitHub (.com or Enterprise) API token to use. Must be
provided.
GIST_TOKEN - the GitHub (.com or Enterprise) API token to use to clone the build
Gists.
```

Add surf-publish

---

README.md
package.json
src/download-release-cli.js
src/download-release-main.js
src/github-api.js

This PR adds a new `surf-download` command that downloads all of the artifacts for a Release from GitHub (whether Surf created them or not)
```
Usage: surf-download -r http://github.com/some/repo -t some-tag
Download all of the artifacts for a given Release
Options:
--target    The directory to download files to
-r, --repo  The repository to clone
-t, --tag   The tag to download releases for
Some useful environment variables:
GITHUB_TOKEN - the GitHub (.com or Enterprise) API token to use. Must be
provided.
```

Add surf-download

---

src/github-api.js

This PR makes surf-server and surf-client only fetch open PRs, which is much, much faster than trying to fetch all refs

Make ref servers fast again

---

package.json
src/git-api.js

Surf build dirs would hit MAX_PATH issues on Windows since Temp is already a decent chunk in, then we'd try to `npm install` in it. Instead, use something shorter

Short build directory names

---

src/github-api.js

For PRs from forks. using the `head.repo.full_name` makes sure the ref downloading/checking works as intended (it doesn't seem to affect feature-branch PRs).
Also added a bit more info to the debug message as well as made sure it's not printing `undefined`.
This was a simple attempt at fixing - I tested against our repo (with various PRs from forks) and it worked as intended - let me know if there's a better/cleaner way to do it.
Fixes #44

Use the ref's repo name when checking refs

---

README.md

There may be more changes needed, but this one should help new users get up and running faster. `surf-client` no longer exists, use `surf-run` instead.

Update Readme to reflect code changes

---

.travis.yml
src/build-api.js
src/build-discoverers/danger.js

This PR fixes behaivor of `getAffinityRootDir` for danger to return correct affinity number for certain cases. Discoverer expects affinity as number, while lookup for danger can possibly return `undefined` instead - makes discoverer think danger is available. Also updated discoverer to check value is available as well.

Correct bundle lookup affinity when does not exist

---

src/build-api.js

If a discoverer returned 0 for its affinity, such as the case of the Danger discoverer when it
isn't supposed to run, the current filter would add it anyway since zero evaluates to false.
Fixes #53.

Don't add discoverers with an affinity of 0.

---

src/github-api.js

This PR drastically reduces the number of GitHub API calls we make, by caching ref information by SHA1, then using the PR info to see if we've already seen this sha before.

Use the PR information to cache refs 

---

src/build-api.js
src/git-api.js

This PR allows you to run `surf-clean` inside of `surf-build` by escaping the fake TMPDIR we set up

Allow surf-clean to be run inside surf-build successfully

---

src/build-api.js
src/build-project-cli.js
src/build-project-main.js
src/git-api.js

This PR cleans up a bunch of things:
1. Surf was printing the build output twice on failures which is silly
1. Surf was saving the build output as a string, which will overflow on large builds. Instead, stream it to disk / stdout
1. On build failure, we'd throw an error, which Surf would then stomp our GH status with a "Errored" status

Don't report failed builds as errors

---

README.md

`surf-server` isn't a thing anymore. Remove it from the README and usage examples.

Cleanup README to remove surf-server.

---

src/publish-tag-main.js

Uploading from failed statuses has unintended side-effects. For example, if you restart the same build multiple times, you can get stuck with a bunch of dupe files that cause `surf-publish` to error out.

Only upload artifacts from successful statuses

---

src/job-installers/launchd.plist.in

OP #65: surf-install doesn't work on OSX
The problem was that the first argument in the ProgramArguments array needs to be the command itself. 
I think this change to the template does the job.

Add the command as first element in ProgramArguments array, fixes #65

---

README.md

The privileges of the $GITHUB_TOKEN used are critical; the assumption in the readme is that the repo-owning user is generating the token, but that may not be the case. (I wanted to switch my build to a machine user and went down in flames :)
This just updates the README.md to mention the privileges required of the token-creating user.
Side-note: In the future it might be worth moving from GITHUB_TOKEN to SURF_GITHUB_TOKEN or some such, since there are many different tokens in my environment, and the fewer that have undifferentiated names, the better. homebrew, for example, uses HOMEBREW_GITHUB_TOKEN.

Minor readme update: Mention need for write priv on token

---

.travis.yml
src/build-monitor.ts
src/run-on-every-ref-cli.ts
src/run-on-every-ref-main.ts

This PR gives you a flag to be able to disable cancelling builds when pushes happen, because for some crappy build systems this corrupts their global state

Disable build cancellation

---

fixtures/diffstat.txt
src/build-api.ts
src/build-discover-base.ts
src/build-discoverers/autotools.ts
src/build-discoverers/build-script.ts
src/build-discoverers/cmake.ts
src/build-discoverers/danger.ts
src/build-discoverers/dotnet.ts
src/build-discoverers/monorepo.ts
src/build-discoverers/npm.ts
src/build-discoverers/rust.ts
src/build-discoverers/xcode.ts
src/git-api.ts
src/promise-array.ts
test/git-api.ts

This PR adds the ability to build >1 project out of the same repository. To do this, declare a top-level `.surf.json` file:
```json
{
"projects": ["src/project1", "src/project2"]
}
```
Surf will now build the entire set of projects on the master branch, and attempt to only build projects whose files have changed in PRs

Simple Monorepo support
